# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: S.OWL
email: we.sss.you@gmail.com
description: S.OWL - 성공회대학교 소프트웨어 연구개발 동아리
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://s-owl.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  s-owl

# Build settings
markdown: kramdown
